import 'package:get/get.dart';

class LocaleString extends Translations{
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
    'en_US':{
      'Dilshodjon Haydarov':'Dilshodjon Haydarov',

      'hello':'Hello World',
      'message':'Welcome to Proto Coders Point',
      'title':'Flutter Language - Localization',
      'sub':'Subscribe Now',
      'changelang':'Change Language',
      'f.i.sh':'F.I.SH:',
      'Kiriting':'Enter',
      'Telefon raqam':'Phone number',
      'Parolni kiriting':'Enter password',
      'Parolni takrorlang':'Repeat password',
      'Ommaviy oferta':'Public offer',
      'shartlariga roziman':'I agree to the terms',
      'Ro\'yxatdan o\'tish':'Register',
      'Ro\'yxatdan o\'tganmisiz?':'Have you registered?',
      'Kirish':'Login',
      'Parol':'Password',
      'Eslab qolish':'Remember me',
      'Parolni unutdingizmi?':'Forgot your password?',
      'SMS kod' : 'SMS code',
      'SMS xabar kelmadimi?':'Didn\'t receive an SMS message?',
      'Qayta yuborish' : 'Resend',
      'Tasdiqlash' : 'Confirm',
      'Parolni tiklash':'Reset password',
      'SMS kodni yuborish':'Send SMS code',

      //validation
      'Xatolik':'Error',
      'Bunday foydalanuvchi mavjud!':'User already exists!',
      'Server bilan bog\'lanishda xatolik!':'Error connecting to the server!',
      'Parol kamida 6 ta belgidan iborat bo\'lishi kerak!':'Password must be at least 6 characters long!',
      'f.i.sh kiriting!':'Enter F.I.SH!',
      'Parolni takrorlangan qismi mos kelmadi!':'The repeated part of the password did not match!',
      'Telefon raqamni kiriting!':'Enter your phone number!',
      'Parolni kiriting!':'Enter your password!',
      'Parolni takrorlang!':'Repeat the password!',
      'Parollar mos kelmadi!':'Passwords did not match!',
      'Ommaviy oferta shartlariga rozilik bildirishingiz kerak!': 'You must agree to the terms of the public offer!',
      'SMS kodni kiriting!':'Enter the SMS code!',
      'Muvaffaqiyatli' : 'Success',
      'Parolni muvaffaqiyatli o\'zgartirdingiz!':'You have successfully changed your password!',
      'Bunday foydalanuvchi mavjud emas!':'User not found!',
      'Noto\'g\'ri parol kiritdingiz!':'You entered the wrong password!',
      'Ma\'lumotlar yo\'q!':'No data!',
      'Internet aloqasi yo\'q':'No Internet connection!',
      'Sotuvda mavjud': 'In the store',
      'Sotuvda mavjud emas': 'Not in the store',

      //Sample page
      'Kitoblarni izlash':'Search for books',
      'Kategoriya':'Category',
      'Barchasi':'All',
      'Elektron kitoblar':'E-books',
      'Asosiy':'Main',
      'Do\'kon':'Store',
      'Kutubxona':'Library',
      'Savatcha':'Cart',
      'Sahifam':'My page',
      'Audio kitoblar':'Audio books',
      'Iqtiboslar':'Favorites',
      'Mualliflar':'Authors',
      'Top':'Top',
      'Kitoblar':'Books',
      'Do‘kon mahsulotlari':'Store products',
      'Sizni yuzlab jozibador hikoyalar kutmoqda':'Hundreds of exciting stories are waiting for you',
      'Sevimli janrlaringizni o\'rganing':'Learn your favorite genres',

      //Sahifam page
      'Profilni tahrirlash':'Edit profile',
      'Mening kitoblarim':'My books',
      'Buyurtmalar':'Orders',
      'Chegirmalar':'Discounts',
      'Promokod':'Promocode',
      'Tilni o\'zgartirish':'Change language',
      'O\'qish turi' : 'Reading mode',
      'Tungi rejim':'Night mode',
      'Dastur haqida':'About the program',
      'Biz bilan bog\'lanish':'Contact us',
      'Ilovadan chiqish':'Exit the application',
      'Shaxsiy ma\'lumotlar':'Personal information',

      //detail page
      'ta izoh':'Comment',
      'ta ko\'rilgan':'Viewed',
      'Xarid':'Buy',
      'Izoh':'Comment',
      'Izohlar':'Comments',
      'Tafsilotlar':'Details',
      'Tavsif':'Description',
      'Sizning fikringiz':'Your opinion',
      'Jo\'natish':'Send',
      'Muallif':'Author',
      'Qog\'ozli kitob':'Paper book',
      'Elektron kitob':'E-book',
      'Audio kitob':'Audio book',
      'Baholang':'Rating',
      'Mualif haqida':'About the author',
      'Tavsiya etiladi':'Recommended',
      'Izohlar yo\'q':'No comments',
      'Tahrirlash':'Edit',
      'O\'chirish':'Delete',
      'Saqlash':'Save',

    },
    'ru_RU':{
      'Dilshodjon Haydarov':'Дильшоджон Хайдаров',
      'hello': 'Привет, мир',
      'message':'Добро пожаловать в Proto Coders Point',
      'title':'Язык Flutter - Локализация',
      'subscribe':'Подписывайтесь сейчас',
      'changelang':'Изменить язык',
      'f.i.sh':'Ф.И.О:',
      'Kiriting':'Введите',
      'Telefon raqam':'Номер телефона',
      'Parolni kiriting':'Введите пароль',
      'Parolni takrorlang':'Повторите пароль',
      'Ommaviy oferta':'Публичная оферта',
      'shartlariga roziman':'Я согласен с условиями',
      'Ro\'yxatdan o\'tish':'Регистрация',
      'Ro\'yxatdan o\'tganmisiz?':'Вы зарегистрированы?',
      'Kirish':'Вход',
      'Parol':'Пароль',
      'Eslab qolish':'Запомнить меня',
      'Parolni unutdingizmi?':'Забыли пароль?',
      'SMS kod' : 'SMS код',
      'SMS xabar kelmadimi?':'Не пришло SMS сообщение?',
      'Qayta yuborish' : 'Отправить повторно',
      'Tasdiqlash' : 'Подтвердить',
      'Parolni tiklash':'Сбросить пароль',
      'SMS kodni yuborish':'Отправить SMS код',

      //validation
      'Xatolik':'Ошибка',
      'Bunday foydalanuvchi mavjud!':'Пользователь уже существует!',
      'Server bilan bog\'lanishda xatolik!':'Ошибка подключения к серверу!',
      'Parol kamida 6 ta belgidan iborat bo\'lishi kerak!':'Пароль должен содержать не менее 6 символов!',
      'f.i.sh kiriting!':'Введите Ф.И.О!',
      'Parolni takrorlangan qismi mos kelmadi!':'Повторная часть пароля не совпала!',
      'Telefon raqamni kiriting!':'Введите номер телефона!',
      'Parolni kiriting!':'Введите пароль!',
      'Parolni takrorlang!':'Повторите пароль!',
      'Parollar mos kelmadi!':'Пароли не совпали!',
      'Ommaviy oferta shartlariga rozilik bildirishingiz kerak!': 'Вы должны согласиться с условиями публичной оферты!',
      'SMS kodni kiriting!':'Введите SMS код!',
      'Muvaffaqiyatli' : 'Успешно',
      'Parolni muvaffaqiyatli o\'zgartirdingiz!':'Вы успешно изменили пароль!',
      'Bunday foydalanuvchi mavjud emas!':'Пользователь не найден!',
      'Noto\'g\'ri parol kiritdingiz!':'Вы ввели неправильный пароль!',
      'Ma\'lumotlar yo\'q!':'Нет данных!',
      'Internet aloqasi yo\'q':'Нет интернета',
      'Sotuvda mavjud': 'В наличии',
      'Sotuvda mavjud emas': 'Нет в наличии',

      //Sample page
      'Kitoblarni izlash':'Поиск книг',
      'Kategoriya':'Категория',
      'Barchasi':'Все',
      'Elektron kitoblar':'Электронные книги',
      'Asosiy':'Главный',
      'Do\'kon':'Магазин',
      'Kutubxona':'Библиотека',
      'Savatcha':'Корзина',
      'Sahifam':'Моя страница',
      'Audio kitoblar':'Аудиокниги',
      'Iqtiboslar':'Избранное',
      'Mualliflar':'Авторы',
      'Top':'Топ',
      'Kitoblar':'Книги',
      'Do‘kon mahsulotlari':'Товары магазина',
      'Sizni yuzlab jozibador hikoyalar kutmoqda':'Сотни захватывающих историй ждут вас',
      'Sevimli janrlaringizni o\'rganing':'Sevimli janrlaringizni o\'rganing',

      //Sahifam page
      'Profilni tahrirlash':'Редактировать профиль',
      'Mening kitoblarim':'Мои книги',
      'Buyurtmalar':'Заказы',
      'Chegirmalar':'Скидки',
      'Promokod':'Промокод',
      'Tilni o\'zgartirish':'Изменить язык',
      'O\'qish turi' : 'Тип чтения',
      'Tungi rejim':'Ночной режим',
      'Dastur haqida':'О программе',
      'Biz bilan bog\'lanish':'Связаться с нами',
      'Ilovadan chiqish':'Выйти из приложения',
      'Shaxsiy ma\'lumotlar':'Персональные данные',

      //detail page
      'ta izoh':'Комментарий',
      'ta ko\'rilgan':'Просмотрено',
      'Xarid':'Купить',
      'Izoh':'Комментарий',
      'Izohlar':'Комментарии',
      'Tafsilotlar':'Детали',
      'Tavsif':'Описание',
      'Sizning fikringiz':'Ваше мнение',
      'Jo\'natish':'Отправить',
      'Muallif':'Автор',
      'Qog\'ozli kitob':'Бумажная книга',
      'Elektron kitob':'Электронная книга',
      'Audio kitob':'Аудиокнига',
      'Baholang':'Оценка',
      'Mualif haqida':'Об авторе',
      'Tavsiya etiladi':'Рекомендуется',
      'Izohlar yo\'q':'Комментарии отсутствуют',
      'Tahrirlash':'Редактировать',
      'O\'chirish':'Удалить',
      'Saqlash':'Сохранить',

    },
    'uz_UZ':{
      'Dilshodjon Haydarov':'Dilshodjon Haydarov',

      'hello': 'Salom Dunyo',
      'message':'Proto Coders Pointga xush kelibsiz',
      'title':'Flutter Tili - Lokallashtirish',
      'subscribe':'Hozir obuna bo\'ling',
      'changelang':'Tilni o\'zgartirish',
      'f.i.sh':'F.I.SH:',
      'Kiriting':'Kiriting',
      'Telefon raqam':'Telefon raqam',
      'Parolni kiriting':'Parolni kiriting',
      'Parolni takrorlang':'Parolni takrorlang',
      'Ommaviy oferta':'Ommaviy oferta',
      'shartlariga roziman':'shartlariga roziman',
      'Ro\'yxatdan o\'tish':'Ro\'yxatdan o\'tish',
      'Ro\'yxatdan o\'tganmisiz?':'Ro\'yxatdan o\'tganmisiz?',
      'Kirish':'Kirish',
      'Parol':'Parol',
      'Eslab qolish':'Eslab qolish',
      'Parolni unutdingizmi?':'Parolni unutdingizmi?',
      'SMS kod' : 'SMS kod',
      'SMS xabar kelmadimi?':'SMS xabar kelmadimi?',
      'Qayta yuborish' : 'Qayta yuborish',
      'Tasdiqlash' : 'Tasdiqlash',
      'Parolni tiklash':'Parolni tiklash',
      'SMS kodni yuborish':'SMS kodni yuborish',

      //validation
      'Xatolik':'Xatolik',
      'Bunday foydalanuvchi mavjud!':'Bunday foydalanuvchi mavjud!',
      'Server bilan bog\'lanishda xatolik!':'Server bilan bog\'lanishda xatolik!',
      'Parol kamida 6 ta belgidan iborat bo\'lishi kerak!':'Parol kamida 6 ta belgidan iborat bo\'lishi kerak!',
      'f.i.sh kiriting!':'f.i.sh kiriting!',
      'Parolni takrorlangan qismi mos kelmadi!':'Parolni takrorlangan qismi mos kelmadi!',
      'Telefon raqamni kiriting!':'Telefon raqamni kiriting!',
      'Parolni kiriting!':'Parolni kiriting!',
      'Parolni takrorlang!':'Parolni takrorlang!',
      'Parollar mos kelmadi!':'Parollar mos kelmadi!',
      'Ommaviy oferta shartlariga rozilik bildirishingiz kerak!': 'Ommaviy oferta shartlariga rozilik bildirishingiz kerak!',
      'SMS kodni kiriting!':'SMS kodni kiriting!',
      'Muvaffaqiyatli' : 'Muvaffaqiyatli',
      'Parolni muvaffaqiyatli o\'zgartirdingiz!':'Parolni muvaffaqiyatli o\'zgartirdingiz!',
      'Bunday foydalanuvchi mavjud emas!':'Bunday foydalanuvchi mavjud emas!',
      'Noto\'g\'ri parol kiritdingiz!':'Noto\'g\'ri parol kiritdingiz!',
      'Ma\'lumotlar yo\'q!':'Ma\'lumotlar yo\'q!',
      'Internet aloqasi yo\'q':'Internet aloqasi yo\'q',
      'Sotuvda mavjud': 'Sotuvda mavjud',
      'Sotuvda mavjud emas': 'Sotuvda mavjud emas',

      //Sample page
      'Kitoblarni izlash':'Kitoblarni izlash',
      'Kategoriya':'Kategoriya',
      'Barchasi':'Barchasi',
      'Elektron kitoblar':'Elektron kitoblar',
      'Asosiy':'Asosiy',
      'Do\'kon':'Do\'kon',
      'Kutubxona':'Kutubxona',
      'Savatcha':'Savatcha',
      'Sahifam':'Sahifam',
      'Audio kitoblar':'Audio kitoblar',
      'Iqtiboslar':'Iqtiboslar',
      'Mualliflar':'Mualliflar',
      'Top':'Top',
      'Kitoblar':'Kitoblar',
      'Do‘kon mahsulotlari':'Do‘kon mahsulotlari',
      'Sizni yuzlab jozibador hikoyalar kutmoqda':'Sizni yuzlab jozibador hikoyalar kutmoqda',
      'Sevimli janrlaringizni o\'rganing':'Sevimli janrlaringizni o\'rganing',

      //Sahifam page
      'Profilni tahrirlash':'Profilni tahrirlash',
      'Mening kitoblarim':'Mening kitoblarim',
      'Buyurtmalar':'Buyurtmalar',
      'Chegirmalar':'Chegirmalar',
      'Promokod':'Promokod',
      'Tilni o\'zgartirish':'Tilni o\'zgartirish',
      'O\'qish turi' : 'O\'qish turi',
      'Tungi rejim':'Tungi rejim',
      'Dastur haqida':'Dastur haqida',
      'Biz bilan bog\'lanish':'Biz bilan bog\'lanish',
      'Ilovadan chiqish':'Ilovadan chiqish',
      'Shaxsiy ma\'lumotlar':'Shaxsiy ma\'lumotlar',

      //detail page
      'ta izoh':'ta izoh',
      'ta ko\'rilgan':'ta ko\'rilgan',
      'Xarid':'Xarid',
      'Izoh':'Izoh',
      'Izohlar':'Izohlar',
      'Tafsilotlar':'Tafsilotlar',
      'Tavsif':'Tavsif',
      'Sizning fikringiz':'Sizning fikringiz',
      'Jo\'natish':'Jo\'natish',
      'Muallif':'Muallif',
      'Qog\'ozli kitob':'Qog\'ozli kitob',
      'Elektron kitob':'Elektron kitob',
      'Audio kitob':'Audio kitob',
      'Baholang':'Baholang',
      'Mualif haqida':'Mualif haqida',
      'Tavsiya etiladi':'Tavsiya etiladi',
      'Izohlar yo\'q':'Izohlar yo\'q',
      'Tahrirlash':'Tahrirlash',
      'O\'chirish':'O\'chirish',
      'Saqlash':'Saqlash',

    },
    'oz_OZ':{
      'Dilshodjon Haydarov':'Дильшоджон Хайдаров',
      'hello': 'Салом Дунё',
      'message':'Прото Кодерс Пойнтга хуш келибсиз',
      'title':'Флуттер Тили - Локаллаштириш',
      'subscribe':'Ҳозир обуна бўлинг',
      'changelang':'Тилни ўзгартириш',
      'f.i.sh':'Ф.И.Ш:',
      'Kiriting':'Киритинг',
      'Telefon raqam':'Телефон рақам',
      'Parolni kiriting':'Паролни киритинг',
      'Parolni takrorlang':'Паролни тақрорланг',
      'Ommaviy oferta':'Оммавий оферта',
      'shartlariga roziman':'шартларига розиман',
      'Ro\'yxatdan o\'tish':'Рўйхатдан ўтиш',
      'Ro\'yxatdan o\'tganmisiz?':'Рўйхатдан ўтганмисиз?',
      'Kirish':'Кириш',
      'Parol':'Парол',
      'Eslab qolish':'Еслаб қолиш',
      'Parolni unutdingizmi?':'Паролни унутдингизми?',
      'SMS kod' : 'SMS код',
      'SMS xabar kelmadimi?':'SMS хабар келмадими?',
      'Qayta yuborish' : 'Қайта юбориш',
      'Tasdiqlash' : 'Тасдиқлаш',
      'Parolni tiklash':'Паролни тиклаш',
      'SMS kodni yuborish':'SMS кодни юбориш',

      //validation
      'Xatolik':'Хатолик',
      'Bunday foydalanuvchi mavjud!':'Бундай фойдаланувчи мавжуд!',
      'Server bilan bog\'lanishda xatolik!':'Сервер билан боғланишда хатолик!',
      'Parol kamida 6 ta belgidan iborat bo\'lishi kerak!':'Парол камида 6 та белгидан иборат бўлиши керак!',
      'f.i.sh kiriting!':'Ф.И.Ш киритинг!',
      'Parolni takrorlangan qismi mos kelmadi!':'Паролни тақрорланган қисми мос келмади!',
      'Telefon raqamni kiriting!':'Телефон рақамни киритинг!',
      'Parolni kiriting!':'Паролни киритинг!',
      'Parolni takrorlang!':'Паролни тақрорланг!',
      'Parollar mos kelmadi!':'Пароллар мос келмади!',
      'Ommaviy oferta shartlariga rozilik bildirishingiz kerak!': 'Оммавий оферта шартларига розилик билдиришингиз керак!',
      'SMS kodni kiriting!':'SMS кодни киритинг!',
      'Muvaffaqiyatli' : 'Муваффақиятли',
      'Parolni muvaffaqiyatli o\'zgartirdingiz!':'Паролни муваффақиятли ўзгартирдингиз!',
      'Bunday foydalanuvchi mavjud emas!':'Бундай фойдаланувчи мавжуд емас!',
      'Noto\'g\'ri parol kiritdingiz!':'Ното\'г\'ри парол киритдингиз!',
      'Ma\'lumotlar yo\'q!':'Маълумотлар йўқ!',
      'Internet aloqasi yo\'q': 'Интернет алоқаси йўқ',
      'Sotuvda mavjud': 'Сотувда мавжуд',
      'Sotuvda mavjud emas': 'Сотувда мавжуд емас',

      //Sample page
      'Kitoblarni izlash':'Китобларни излаш',
      'Kategoriya':'Категория',
      'Barchasi':'Барчаси',
      'Elektron kitoblar':'Электрон китоблар',
      'Asosiy':'Асосий',
      'Do\'kon':'Дўкон',
      'Kutubxona':'Кутубхона',
      'Savatcha':'Саватча',
      'Sahifam':'Саҳифам',
      'Audio kitoblar':'Аудио китоблар',
      'Iqtiboslar':'Иқтибослар',
      'Mualliflar':'Муаллифлар',
      'Top':'Топ',
      'Kitoblar':'Китоблар',
      'Do‘kon mahsulotlari':'Дўкон маҳсулотлари',
      'Sizni yuzlab jozibador hikoyalar kutmoqda':'Сизни юзлаб жозибадор ҳикоялар кутмоқда',
      'Sevimli janrlaringizni o\'rganing':'Севимли жанрларингизни ўрганинг',

      //Sahifam page
      'Profilni tahrirlash':'Профилни таҳрирлаш',
      'Mening kitoblarim':'Менинг китобларим',
      'Buyurtmalar':'Буюртмалар',
      'Chegirmalar':'Чегирмалар',
      'Promokod':'Промокод',
      'Tilni o\'zgartirish':'Тилни ўзгартириш',
      'O\'qish turi' : 'Ўқиш тури',
      'Tungi rejim':'Тунги режим',
      'Dastur haqida':'Дастур ҳақида',
      'Biz bilan bog\'lanish':'Биз билан боғланиш',
      'Ilovadan chiqish':'Иловадан чиқиш',
      'Shaxsiy ma\'lumotlar':'Шахсий маълумотлар',

      //detail page
      'ta izoh':'та изоҳ',
      'ta ko\'rilgan':'та кўрилган',
      'Xarid':'Харид',
      'Izoh':'Изоҳ',
      'Izohlar':'Изоҳлар',
      'Tafsilotlar':'Тафсилотлар',
      'Tavsif':'Тавсиф',
      'Sizning fikringiz':'Сизнинг фикрингиз',
      'Jo\'natish':'Жўнатиш',
      'Muallif':'Муаллиф',
      'Qog\'ozli kitob':'Қоғозли китоб',
      'Elektron kitob':'Электрон китоб',
      'Audio kitob':'Аудио китоб',
      'Baholang':'Баҳоланг',
      'Mualif haqida':'Муаллиф ҳақида',
      'Tavsiya etiladi':'Тавсия этилади',
      'Izohlar yo\'q':'Изоҳлар йўқ',
      'Tahrirlash':'Таҳрирлаш',
      'O\'chirish':'Очириш',
      'Saqlash':'Сақлаш',
    }
  };

}